name:                haskell-example
version:             0.1.0.0
github:              "githubuser/haskell-example"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-example#readme>

dependencies:
- base >= 4.7 && < 5
- random


library:
  source-dirs: src
  exposed-modules: 
  - Cp3
  - Lib
  - Elementos.Ninos
  - Elementos.Corral
  - Elementos.Suciedad
  - Elementos.Robot
  - Elementos.Obstaculo
  - Ambiente.Ambiente
  - Utils
  

executables:
  haskell-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-example

tests:
  haskell-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-example
